# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'AdmobBannerBestPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdmobBannerBestPractice
pod 'SnapKit'
pod 'Google-Mobile-Ads-SDK'
end
