# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'GlobalNewsView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GlobalNewsView
pod 'Alamofire'
pod 'SDWebImage'
pod 'SnapKit'
pod 'IQPullToRefresh'
pod "SkeletonView"
pod 'CHIPageControl/Jaloro'
pod 'Google-Mobile-Ads-SDK'
end
