disabled_rules: # ปิดการใช้งานกฎที่ไม่ต้องการ
  - trailing_whitespace
  - identifier_name
  - cyclomatic_complexity

opt_in_rules: # กฎที่ควรใช้เพิ่มเติมตามแนวทาง API Design Guidelines
  - empty_count
  - empty_string
  - closure_spacing
  - closure_end_indentation
  - operator_usage_whitespace

# กำหนดเส้นทางที่ต้องการตรวจสอบ
included:
  - PlayPlayPlus # ปรับให้เป็นชื่อโฟลเดอร์ที่เก็บไฟล์ Swift ของคุณ

excluded: # เส้นทางที่ต้องการยกเว้นไม่ตรวจสอบ
  - Carthage
  - Pods
  - SwiftLint/Common/3rdPartyLib

line_length:
  warning: 150 # ตาม API Design Guidelines
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 100
  error: 200

function_parameter_count:
  warning: 5
  error: 8

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

# identifier_name:
#   min_length: 3
#   max_length: 40
#   excluded:
#     - id
#     - URL
#     - API
#     - JSON
#     - vc

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

vertical_whitespace:
  max_empty_lines: 1
reporter: "xcode"