# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoUMP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoUMP
pod 'GoogleUserMessagingPlatform'
pod 'Google-Mobile-Ads-SDK'
pod 'SnapKit'
end
